# Script mode helper of EmbedFiles.cmake: cmake -DOUTPUT=... -DFUNCTION=... -DHEADER=...
# -DINPUTS=a|b|c -P EmbedFilesScript.cmake

string(REPLACE "|" ";" inputs "${INPUTS}")

string(REGEX MATCH "^(.*)::([^:]+)$" _ "${FUNCTION}")
set(namespace "${CMAKE_MATCH_1}")
set(function_name "${CMAKE_MATCH_2}")

set(arrays "")
set(entries "")
set(index 0)
foreach(input IN LISTS inputs)
    get_filename_component(name "${input}" NAME)
    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    # 0x.., bytes, 24 per line.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n    " bytes "${bytes}")
    string(APPEND arrays "constexpr unsigned char kFile${index}[] = {\n    ${bytes}0x00};\n")
    string(APPEND entries
        "    EmbeddedFile{\"${name}\", std::string_view(reinterpret_cast<const char*>(kFile${index}), ${size})},\n")
    math(EXPR index "${index} + 1")
endforeach()

set(content "// Generated by cmake/EmbedFiles.cmake from:\n")
foreach(input IN LISTS inputs)
    get_filename_component(name "${input}" NAME)
    string(APPEND content "//   ${name}\n")
endforeach()
string(APPEND content "// Do not edit.

#include \"${HEADER}\"

#include <array>
#include <span>
#include <string_view>

namespace ${namespace} {
namespace {

${arrays}
} // namespace

std::span<const EmbeddedFile> ${function_name}() {
    static const std::array<EmbeddedFile, ${index}> files{{
${entries}    }};
    return files;
}

} // namespace ${namespace}
")

# Only touch the output when it changes, so dependants are not rebuilt needlessly.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
